### ISSUE TITLE
Your great wayland-clients book

### ISSUE THREAD

**Issue by fredvs** [bugaevc/writing-wayland-clients#2]
Congratulation for the excellent book: https://bugaevc.gitbooks.io/writing-wayland-clients

I use some of your code for Pascal demos:
https://github.com/fredvs/wayland-pascal

In chapter **Global objects**, in the code those methods are used: `_wl_display_get_registry_' and '_wl_registry_add_listener_'

But I have error at linking, those methods are not found.

In my system those methods are not defined:
$ nm -D /usr/lib/x86_64-linux-gnu/libwayland-client.so

00000000000076c0 T wl_array_add
000000000000a4d0 T wl_array_copy
0000000000007560 T wl_array_init
0000000000007580 T wl_array_release
000000000000fbc0 D wl_buffer_interface
000000000000fd40 D wl_callback_interface
000000000000eae0 D wl_compositor_interface
000000000000fac0 D wl_data_device_interface
000000000000ebe0 D wl_data_device_manager_interface
000000000000fb00 D wl_data_offer_interface
000000000000fb40 D wl_data_source_interface
0000000000006cd0 T wl_display_cancel_read
000000000000a170 T wl_display_connect
0000000000009f60 T wl_display_connect_to_fd
0000000000007050 T wl_display_create_queue
00000000000075a0 T wl_display_disconnect
0000000000008e50 T wl_display_dispatch
0000000000007500 T wl_display_dispatch_pending
0000000000008d10 T wl_display_dispatch_queue
0000000000007440 T wl_display_dispatch_queue_pending
0000000000006dc0 T wl_display_flush
0000000000006d30 T wl_display_get_error
0000000000006cc0 T wl_display_get_fd
0000000000006d60 T wl_display_get_protocol_error
000000000000fd80 D wl_display_interface
0000000000007430 T wl_display_prepare_read
00000000000073c0 T wl_display_prepare_read_queue
0000000000007a80 T wl_display_read_events
0000000000009f50 T wl_display_roundtrip
0000000000009e50 T wl_display_roundtrip_queue
0000000000007350 T wl_event_queue_destroy
000000000000f980 D wl_keyboard_interface
0000000000007340 T wl_list_empty
0000000000007040 T wl_list_init
0000000000007090 T wl_list_insert
0000000000007510 T wl_list_insert_list
0000000000007310 T wl_list_length
00000000000070b0 T wl_list_remove
0000000000007030 T wl_log_set_handler_client
000000000000fa00 D wl_output_interface
000000000000f9c0 D wl_pointer_interface
0000000000006c60 T wl_proxy_add_dispatcher
0000000000006bf0 T wl_proxy_add_listener
0000000000008fa0 T wl_proxy_create
0000000000006f50 T wl_proxy_create_wrapper
0000000000007a10 T wl_proxy_destroy
0000000000006ec0 T wl_proxy_get_class
0000000000006e90 T wl_proxy_get_id
0000000000006c50 T wl_proxy_get_listener
0000000000006eb0 T wl_proxy_get_tag
0000000000006e70 T wl_proxy_get_user_data
0000000000006e80 T wl_proxy_get_version
00000000000099c0 T wl_proxy_marshal
0000000000009c00 T wl_proxy_marshal_array
00000000000099b0 T wl_proxy_marshal_array_constructor
0000000000009990 T wl_proxy_marshal_array_constructor_versioned
0000000000008ff0 T wl_proxy_marshal_array_flags
0000000000009ae0 T wl_proxy_marshal_constructor
0000000000009c10 T wl_proxy_marshal_constructor_versioned
0000000000009d30 T wl_proxy_marshal_flags
0000000000006ed0 T wl_proxy_set_queue
0000000000006ea0 T wl_proxy_set_tag
0000000000006e60 T wl_proxy_set_user_data
0000000000006fe0 T wl_proxy_wrapper_destroy
000000000000fc00 D wl_region_interface
000000000000fc80 D wl_registry_interface
000000000000fa80 D wl_seat_interface
000000000000ec40 D wl_shell_interface
000000000000fa40 D wl_shell_surface_interface
000000000000eb60 D wl_shm_interface
000000000000fb80 D wl_shm_pool_interface
000000000000ecc0 D wl_subcompositor_interface
000000000000f900 D wl_subsurface_interface
000000000000fc40 D wl_surface_interface
000000000000f940 D wl_touch_interface

Do I miss something?

Thanks.

**Comment by bugaevc** [comment]
Hi!

These functions are declared inline in `wayland-client-protocol.h`:

```c
static inline struct wl_registry *
wl_display_get_registry(struct wl_display *wl_display)
{
        struct wl_proxy *registry;

        registry = wl_proxy_marshal_flags((struct wl_proxy *) wl_display,
                         WL_DISPLAY_GET_REGISTRY, &wl_registry_interface, wl_proxy_get_version((struct wl_proxy *) wl_display), 0, NULL);

        return (struct wl_registry *) registry;
}
```

```c
static inline int
wl_registry_add_listener(struct wl_registry *wl_registry,
                         const struct wl_registry_listener *listener, void *data)
{
        return wl_proxy_add_listener((struct wl_proxy *) wl_registry,
                                     (void (**)(void)) listener, data);
}
```

If you're going to use them from Pascal, you're probably going to have to write your own similar wrappers. Alternatively, I guess it could be possible to use the following hack:

```c
// Include the dependency headers before we redefine static...
#include <stdint.h>
#include <stddef.h>

#define static /* nothing */
#include <wayland-client.h>
#undef static
```

and then link the resulting object file into your binary.

**Comment by fredvs** [comment]
Hello and thanks for answer.

Sorry but I am a few lost.

>If you're going to use them from Pascal, you're probably going to have to write your own similar wrappers. Alternatively, I guess it could be possible to use the following hack:

Not sure to understand, should I write that wrapper in C and re-build wayland-client library?
Because I dont see how to do what you proposed in Pascal.

Note that in Pascal we dont use the C wrappers but a Pascal translation of this.

**Comment by fredvs** [comment]
Stupid question: Are those methods _wl_display_get_registry_ and _wl_registry_add_listener_ absolutely needed for your demos or does it a workaround to not use it?

**Comment by fredvs** [comment]
>These functions are declared inline in wayland-client-protocol.h:

Yes, I have noted this and this is the Pascal translation inside _wayland_client_core.pas_ (equivalent to  _wayland-client.h +  wayland-client-protocol.h_ )


```
function  wl_display_get_registry(wl_display_: pwl_display): pwl_registry; cdecl; external;

function  wl_registry_add_listener(wl_registry: pwl_registry;
const listener: Pwl_registry_listener; data: pointer): cint; cdecl; external;

```

And this is your code translated:

```
program WaylandClient_2_globalobjects;

{$mode objfpc}


uses
  ctypes,
  wayland_client,
  wayland_client_core,
  wayland_protocol,
  SysUtils;
  
type
  pwl_registry = pointer; // Define pwl_registry as a pointer type
  
type
  pwl_registry_listener = ^wl_registry_listener;
  wl_registry_listener = record
    global: procedure(data: pointer; registry: pwl_registry; name: LongWord;
                      interface_: PChar; version: LongWord); cdecl;
    global_remove: procedure(data: pointer; registry: pwl_registry; name: LongWord); cdecl;
  end;  

procedure registry_global_handler(data: pointer; registry: pwl_registry;
  name: LongWord; interface_: PChar; version: LongWord); cdecl;
begin
  writeln('interface: ''', interface_, ''', version: ', version, ', name: ', name);
end;

procedure registry_global_remove_handler(data: pointer; registry: pwl_registry;
  name: LongWord); cdecl;
begin
  writeln('removed: ', name);
end;

var
  display: pwl_display;
  registry: pwl_registry;
  registry_listener: wl_registry_listener;

begin
  display := wl_display_connect(nil);
  if display <> nil then
  begin
    registry := wl_display_get_registry(display);

    registry_listener.global := @registry_global_handler;
    registry_listener.global_remove := @registry_global_remove_handler;

    wl_registry_add_listener(registry, @registry_listener, nil);

    while True do
    begin
      wl_display_dispatch(display);
    end;
  end
  else
  begin
    writeln('Error connecting ;(');
    ExitCode := 1;
  end;
end.

```

The prorgam compiles OK but at linking there is those error from the linker:

```
...
/usr/bin/ld: units/WaylandClient_2_globalobjects.o: in function `main':
WaylandClient_2_globalobjects.pas:(.text.n_main+0x25): undefined reference to `wl_display_get_registry'
/usr/bin/ld: WaylandClient_2_globalobjects.pas:(.text.n_main+0x64): undefined reference to `wl_registry_add_listener'
WaylandClient_2_globalobjects.pas(65,1) Error: (9013) Error while linking
WaylandClient_2_globalobjects.pas(65,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
```

**Comment by fredvs** [comment]
Hello.

Yep, it works, the trick was to create a library-for-work with those methods defined and use that library only for linking.  Users dont need it after to execute.

The code:
[wayland_wrapper.c.zip](https://github.com/bugaevc/writing-wayland-clients/files/12703374/wayland_wrapper.c.zip)

The library:
[libwayland_wrapper.so.zip](https://github.com/bugaevc/writing-wayland-clients/files/12703371/libwayland_wrapper.so.zip)

The screenshot on Wayland:
![waylandclient_globalobjects](https://github.com/bugaevc/writing-wayland-clients/assets/3421249/fe93e2b4-80eb-435a-ba6b-263ad9d53989)


And, I must confess, the help that ChatGPT gives me:
[chatgpt_wrapper.txt.zip](https://github.com/bugaevc/writing-wayland-clients/files/12703388/chatgpt_wrapper.txt.zip)

So, perfect, I continue the exploration of your great book.

Many thanks for the help.

Fre;D
